### ISSUE TITLE
train time, inference time input 세팅 맞춰주기?

### ISSUE THREAD

**Issue by gmuffiness** [daintlab/CRAFT-Reimplementation#1]
저번주에 교수님이 inference time에서 데이터 사이즈 관련해서 질문 주셨었는데, 관련해서 다시 살펴보며 생각이 든 점입니다.

https://github.com/daintlab/CRAFT-Reimplementation/blob/craft/utils/inference_boxes.py

위의 official CRAFT의 inference 동작을 보면, resize_aspect_ratio라는 함수를 먼저 거치게 되는데,

https://github.com/daintlab/CRAFT-Reimplementation/blob/fbaa63aebd61c2b290752102cdef4758891b1fb7/data/imgproc.py#L37

여기 해당 함수를 보시면, 아래 사진과 같이 32의 배수가 되도록 캔버스를 둔 뒤에, 이미지를 왼쪽 상단에 붙여넣는 과정이 존재합니다.
위 과정과, normalize를 거친 뒤에 모델에 input으로 들어가게 되는데,

![temp](https://user-images.githubusercontent.com/35298963/142826183-e5b938e0-42c0-4562-90d5-19b4a6af3612.JPG)

하지만, backtime92-Reimplementation 코드에서 train 때는 해당 과정을 수행하지 않는 것 같은데, 이런 세팅을 맞춰주는 과정이 필요하지 않을까요?

**Comment by woans0104** [comment]
아래 그림의 conv stage6의 feature-map size가 input size의 32배로 줄어든 것을 확인할 수 있습니다.  이미지를 처음에 32배수로 맞춰준 것이 이미지의 모서리 부분을 버리지 않고 사용하기 위해서 맞춰 준 것 같고, train 할때 input size가 768*768이니 세팅을 맞춰주는 과정이 이미 되어있다고 저는 생각됩니다 ㅎㅎ 

![image](https://user-images.githubusercontent.com/26699265/142963504-6bca02d2-62a7-4eac-9d36-c70a385a5c97.png)

**Comment by gmuffiness** [comment]
아하 저런 차이로 괴리가 발생하진 않을까..?해서 남겨놨었는데, 다시 생각해보니 큰 문제가 될 것 같지는 않군요!! 감사합니다!
