### ISSUE TITLE
Image.fromarray()

### ISSUE THREAD

**Issue by beopst** [daintlab/CRAFT-Reimplementation#10]
https://github.com/daintlab/CRAFT-Reimplementation/blob/686863f80d973cd5ecfdbae97c250514e22fa6a4/data/dataset.py#L700

이 부분에서 RGB 선언 안해줘도 괜찮은가요?

**Comment by woans0104** [comment]
네! 아래 부분에서 RGB로 converter 하였습니다. 추가로 RGB로  잘 적용된 것을 확인 하였고, synthtext에서도 잘 적용된 것도 확인하였습니다.
https://github.com/daintlab/CRAFT-Reimplementation/blob/686863f80d973cd5ecfdbae97c250514e22fa6a4/data/dataset.py#L591
![image](https://user-images.githubusercontent.com/26699265/149902853-c2000935-520c-45bf-8a13-d3e9df392ed1.png)
