### ISSUE TITLE
normalization 이슈

### ISSUE THREAD

**Issue by beopst** [daintlab/CRAFT-Reimplementation#13]
https://github.com/daintlab/CRAFT-Reimplementation/blob/3218344fc38beaf8c38ede3d7d18701ca84cf99b/data/dataset.py#L723-L725

이 부분을 보면 region score, affinity score, confidence mask를 모두 255로 나눠주는 걸로 되어 있는데 이것들이 다 [0,255] range인가요? confidence mask 같은 경우는 [0,1]인걸로 봤는데 중간에 어느 부분에서 [0,255]로 바뀌나요? 그리고 region/affinity score의 경우 single channel인거죠?

255로 나눠주기 전에 각각의 shape하고 값의 range를 확인해주세요~

**Comment by JihyoKim00** [comment]
https://github.com/daintlab/CRAFT-Reimplementation/blob/3218344fc38beaf8c38ede3d7d18701ca84cf99b/data/dataset.py#L685-L698

이 부분에서 [0,1] range의 confidence mask에 255를 곱해주고 transform을 적용시킨 output으로 confidence mask를 바꿔주면서 range가 [0,255]로 바뀌게 됩니다.

![image](https://user-images.githubusercontent.com/45059321/150374131-9bcc47f9-aabe-41e4-83dc-f08167aaec82.png)
![image](https://user-images.githubusercontent.com/45059321/150374410-9044dd20-711d-40ff-9b67-feb91c8e681f.png)


region score, affinity score, confidence mask 모두 [0,255] range를 가지고, region / affinity score 둘 다 single channel 입니다!
![image](https://user-images.githubusercontent.com/45059321/150373752-17073b0b-da4f-446a-9c23-1e346f2d1dc0.png)
